# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath("./"))
sys.path.insert(0, os.path.abspath("../../"))

import yggdrasil as pkg

RELEASE = os.environ.get("RELEASE", True)

# -- Project information -----------------------------------------------------

project = "Yggdrasil"
author = "Aleksandr Kasian & Nazar Yakovenko"
copyright = f"2024, {author}"
pkg_name = pkg.__name__
pkg_version = str(pkg.__version__)
pkg_location = os.path.dirname(os.path.dirname(pkg.__file__))

# The full version, including alpha/beta/rc tags
version = "master (" + pkg_version + " )"
release = "master"

if RELEASE:
    # Turn 1.11.0aHASH into 1.11
    # Note: the release candidates should no longer have the aHASH suffix, but in any
    # case we wish to leave only major.minor, even for rc builds.
    version = ".".join(pkg_version.split(".")[:2])
    html_title = " ".join((project, version, "documentation"))
    release = version


# -- General configuration ---------------------------------------------------

needs_sphinx = "4.0.2"

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.autodoc.typehints",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.napoleon",
    "sphinx.ext.autosectionlabel",
    # TODO: Use this extensions once baseline ready
    # "sphinx_docsearch",
    # "sphinx_sitemap",
    "sphinx_design",
    "sphinx_togglebutton",
    "sphinx_copybutton",
    "sphinx_design",
]

# build the templated autosummary files
autosummary_generate = True
numpydoc_show_class_members = False

# Theme has bootstrap already
panels_add_bootstrap_css = False

# autosectionlabel throws warnings if section names are duplicated.
# The following tells autosectionlabel to not throw a warning for
# duplicated section names that are in different documents.
autosectionlabel_prefix_document = True

katex_prerender = True

napoleon_use_ivar = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns: list[str] = []

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# Disable docstring inheritance
autodoc_inherit_docstrings = False

# Disable displaying type annotations, these can be very verbose
autodoc_typehints = "none"

# Enable overriding of function signatures in the first line of the docstring.
autodoc_docstring_signature = True


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "pydata_sphinx_theme"

html_theme_options = {
    "use_edit_page_button": False,
    "announcement": False,
    # "navbar_start": ["navbar-ray-logo"],
    "navbar_end": [
        "theme-switcher",
        # "version-switcher",
        # "navbar-icon-links",
        # "navbar-anyscale",
    ],
    # "navbar_center": ["navbar-links"],
    "navbar_align": "left",
    "secondary_sidebar_items": [
        "page-toc",
        # "edit-on-github",
    ],
    # "content_footer_items": [
    #     "csat",
    # ],
    "navigation_depth": 4,
    "pygment_light_style": "stata-dark",
    "pygment_dark_style": "stata-dark",
    "logo": {
        "text": project,
        "image_light": "_static/icons/logo_light.svg",
        "image_dark": "_static/icons/logo_dark.svg",
    },
    # "switcher": {
    #     "json_url": "https://docs.ray.io/en/master/_static/versions.json",
    #     "version_match": os.getenv("READTHEDOCS_VERSION", "master"),
    # },
}

html_sidebars: dict[str, list[str]] = {
    "overview/index": [],
}

intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "torch": ("https://pytorch.org/docs/stable/", None),
    "lightning": ("https://lightning.ai/docs/pytorch/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/reference/", None),
    "pyspark": ("https://spark.apache.org/docs/latest/api/python/", None),
    "torchmetrics": ("https://torchmetrics.readthedocs.io/en/stable/", None),
}
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# -- Options for HTMLHelp output ------------------------------------------
htmlhelp_basename = f"{project}doc"

# -- Options for LaTeX output ---------------------------------------------
latex_elements: dict[str, str] = {}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, f"{pkg_name}.tex", f"{project} Documentation", author, "manual"),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, project, f"{project} Documentation", [author], 1)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        project,
        f"{project} Documentation",
        author,
        project,
        "One line description of project.",
        "Miscellaneous",
    ),
]
