name: Type Checking

on: [push, pull_request]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --extra dev --extra aim

      - name: "Pyright"
        run: uv run pyright

      - name: "Mypy"
        run: uv run mypy src/ tests/
          